import {
  BellRing,
  Building2,
  CalendarCheck2,
  ChevronsUpDown,
  ClipboardList,
  FileClock,
  FolderSearch,
  LayoutDashboard,
  PackageSearch,
  ShieldCheck,
  Sparkles,
  Users2,
  Wrench,
} from "lucide-react"

export type WorkflowStage = {
  slug: string
  path: string
  title: string
  eyebrow: string
  section: string
  summary: string
  icon: typeof LayoutDashboard
  accent: string
  actors: string[]
  inputs: string[]
  checks: string[]
  outputs: string[]
  next: string[]
}

export const workflowStages: WorkflowStage[] = [
  {
    slug: "landing",
    path: "/workflow/landing",
    title: "Landing Page",
    eyebrow: "Entry point",
    section: "Entry",
    summary: "A public-facing launch surface that explains the product and funnels users into the correct access path.",
    icon: LayoutDashboard,
    accent: "from-amber-500 via-orange-500 to-rose-500",
    actors: ["Visitor", "Prospect", "Operator"],
    inputs: ["Brand message", "Product value", "Primary CTA"],
    checks: ["Show the path clearly", "Keep the action hierarchy simple"],
    outputs: ["Authentication handoff", "Workflow preview", "Clear product framing"],
    next: ["authentication", "role-detection"],
  },
  {
    slug: "authentication",
    path: "/workflow/authentication",
    title: "Authentication",
    eyebrow: "Access control",
    section: "Entry",
    summary: "Users sign in, the app verifies identity, and the session is routed to the correct role branch.",
    icon: ShieldCheck,
    accent: "from-sky-500 via-cyan-500 to-emerald-500",
    actors: ["User", "Identity provider", "Session layer"],
    inputs: ["Email or SSO", "Password or token"],
    checks: ["Verify session", "Protect unauthorized paths"],
    outputs: ["Authenticated session", "Role lookup request"],
    next: ["role-detection"],
  },
  {
    slug: "role-detection",
    path: "/workflow/role-detection",
    title: "Role Detection",
    eyebrow: "Branching logic",
    section: "Entry",
    summary: "The app inspects the user's role and sends them either to the super admin branch or the organization admin branch.",
    icon: FolderSearch,
    accent: "from-violet-500 via-indigo-500 to-sky-500",
    actors: ["Session", "Role engine", "Navigator"],
    inputs: ["User record", "Role assignments"],
    checks: ["Is this a super admin?", "Is this an organization admin?"],
    outputs: ["Branch decision", "Role-specific landing"],
    next: ["super-admin", "organization-admin"],
  },
  {
    slug: "super-admin",
    path: "/workflow/super-admin",
    title: "Super Admin",
    eyebrow: "Platform control",
    section: "Organization",
    summary: "The super admin oversees tenants, global settings, and the guardrails for the entire asset platform.",
    icon: Building2,
    accent: "from-slate-500 via-slate-600 to-slate-800",
    actors: ["Platform owner", "Ops lead"],
    inputs: ["Tenant list", "Global policies", "Platform settings"],
    checks: ["Prevent tenant sprawl", "Keep global rules consistent"],
    outputs: ["Tenant configuration", "Administrative oversight"],
    next: ["organization-admin"],
  },
  {
    slug: "organization-admin",
    path: "/workflow/organization-admin",
    title: "Organization Admin",
    eyebrow: "Workspace owner",
    section: "Organization",
    summary: "The organization admin prepares the workspace, shapes the hierarchy, and opens the employee directory.",
    icon: Users2,
    accent: "from-emerald-500 via-teal-500 to-cyan-500",
    actors: ["Organization admin", "HR admin"],
    inputs: ["Tenant context", "Organization profile"],
    checks: ["Confirm organization ownership", "Load workspace defaults"],
    outputs: ["Org setup flow", "Team management tools"],
    next: ["organization-setup", "employee-directory"],
  },
  {
    slug: "organization-setup",
    path: "/workflow/organization-setup",
    title: "Organization Setup",
    eyebrow: "Configuration",
    section: "Organization",
    summary: "The organization profile, departments, asset policies, and approval rules are defined here.",
    icon: Sparkles,
    accent: "from-amber-500 via-lime-500 to-emerald-500",
    actors: ["Admin", "Operations manager"],
    inputs: ["Organization name", "Departments", "Policies"],
    checks: ["Populate core defaults", "Validate policy structure"],
    outputs: ["Configured workspace", "Policy baseline"],
    next: ["employee-directory"],
  },
  {
    slug: "employee-directory",
    path: "/workflow/employee-directory",
    title: "Employee Directory",
    eyebrow: "People data",
    section: "Organization",
    summary: "Employees are imported, reviewed, and prepared for role assignment or asset allocation.",
    icon: ClipboardList,
    accent: "from-cyan-500 via-sky-500 to-blue-500",
    actors: ["HR admin", "Department lead"],
    inputs: ["Employee roster", "Department mapping"],
    checks: ["Prevent duplicates", "Confirm reporting lines"],
    outputs: ["Curated directory", "Assignable employees"],
    next: ["role-assignment"],
  },
  {
    slug: "role-assignment",
    path: "/workflow/role-assignment",
    title: "Role Assignment",
    eyebrow: "Promotion step",
    section: "Organization",
    summary: "The admin promotes employees into department head or asset manager roles based on operational needs.",
    icon: ChevronsUpDown,
    accent: "from-fuchsia-500 via-purple-500 to-indigo-500",
    actors: ["Organization admin", "Department head"],
    inputs: ["Employee record", "Role request"],
    checks: ["Enforce approval", "Record role history"],
    outputs: ["Department head role", "Asset manager role"],
    next: ["asset-registration"],
  },
  {
    slug: "asset-registration",
    path: "/workflow/asset-registration",
    title: "Asset Registration",
    eyebrow: "Asset intake",
    section: "Operations",
    summary: "New assets are registered with metadata, ownership, and lifecycle state before becoming available.",
    icon: PackageSearch,
    accent: "from-teal-500 via-emerald-500 to-green-500",
    actors: ["Asset manager", "Inventory staff"],
    inputs: ["Asset tag", "Serial number", "Purchase metadata"],
    checks: ["Validate uniqueness", "Capture ownership"],
    outputs: ["Available asset record", "Audit-ready metadata"],
    next: ["asset-allocation", "shared-resources"],
  },
  {
    slug: "asset-allocation",
    path: "/workflow/asset-allocation",
    title: "Asset Allocation",
    eyebrow: "Direct assignment",
    section: "Operations",
    summary: "An available asset is allocated to an employee and moves into an active usage state.",
    icon: CalendarCheck2,
    accent: "from-sky-500 via-cyan-500 to-emerald-500",
    actors: ["Asset manager", "Employee"],
    inputs: ["Available asset", "Assignee", "Usage dates"],
    checks: ["Check availability", "Validate allocation rules"],
    outputs: ["Allocated asset", "Use notification"],
    next: ["maintenance"],
  },
  {
    slug: "shared-resources",
    path: "/workflow/shared-resources",
    title: "Shared Resource Booking",
    eyebrow: "Calendar booking",
    section: "Operations",
    summary: "Shared assets are booked through a calendar validation step before the booking is confirmed.",
    icon: CalendarCheck2,
    accent: "from-rose-500 via-pink-500 to-fuchsia-500",
    actors: ["Employee", "Calendar engine"],
    inputs: ["Shared resource", "Requested time slot"],
    checks: ["Check overlap", "Check booking policy"],
    outputs: ["Confirmed booking", "Notification"],
    next: ["maintenance"],
  },
  {
    slug: "maintenance",
    path: "/workflow/maintenance",
    title: "Maintenance Workflow",
    eyebrow: "Condition handling",
    section: "Lifecycle",
    summary: "Maintenance requests are reviewed, approved, and routed to a technician before the asset returns to service.",
    icon: Wrench,
    accent: "from-orange-500 via-amber-500 to-yellow-500",
    actors: ["Asset manager", "Technician"],
    inputs: ["Issue report", "Condition check", "Approval request"],
    checks: ["Approve request", "Assign technician", "Track work order"],
    outputs: ["Under maintenance asset", "Repaired asset"],
    next: ["returns-audit"],
  },
  {
    slug: "returns-audit",
    path: "/workflow/returns-audit",
    title: "Return and Audit",
    eyebrow: "Lifecycle closeout",
    section: "Lifecycle",
    summary: "Returns are inspected, audit cycles verify the inventory, and discrepancies are captured for follow-up.",
    icon: FileClock,
    accent: "from-slate-500 via-zinc-500 to-stone-500",
    actors: ["Asset manager", "Auditor"],
    inputs: ["Return request", "Audit sample", "Inspection results"],
    checks: ["Check condition", "Verify stock count", "Report gaps"],
    outputs: ["Available again", "Discrepancy report"],
    next: ["reports-analytics"],
  },
  {
    slug: "reports-analytics",
    path: "/workflow/reports-analytics",
    title: "Reports & Analytics",
    eyebrow: "Decision support",
    section: "Insights",
    summary: "Operational metrics, usage patterns, and audit findings are turned into reports that help the team act quickly.",
    icon: FileClock,
    accent: "from-indigo-500 via-blue-500 to-cyan-500",
    actors: ["Management", "Operations lead"],
    inputs: ["Events", "Statuses", "Audit results"],
    checks: ["Keep data fresh", "Surface anomalies"],
    outputs: ["Dashboard charts", "Exportable reports"],
    next: ["notifications-logs"],
  },
  {
    slug: "notifications-logs",
    path: "/workflow/notifications-logs",
    title: "Notifications + Activity Logs",
    eyebrow: "System trace",
    section: "Insights",
    summary: "Every significant action emits a notification and lands in an activity log for traceability.",
    icon: BellRing,
    accent: "from-cyan-500 via-sky-500 to-indigo-500",
    actors: ["System", "End users", "Auditors"],
    inputs: ["State transitions", "Approval events", "Warnings"],
    checks: ["Guarantee delivery", "Retain history"],
    outputs: ["Notifications", "Immutable activity trail"],
    next: [],
  },
]

export const workflowGroups = [
  { title: "Entry", slugs: ["landing", "authentication", "role-detection"] },
  { title: "Organization", slugs: ["super-admin", "organization-admin", "organization-setup", "employee-directory", "role-assignment"] },
  { title: "Operations", slugs: ["asset-registration", "asset-allocation", "shared-resources"] },
  { title: "Lifecycle", slugs: ["maintenance", "returns-audit"] },
  { title: "Insights", slugs: ["reports-analytics", "notifications-logs"] },
]

export function getWorkflowStage(slug: string) {
  return workflowStages.find((stage) => stage.slug === slug)
}